name: asqar-safar

services:
  redis:
    image: redis
    ports:
      - 3001:6379
    volumes:
      - ./.docker/redis:/data

  db:
    env_file:
      - .env

    image: 'postgres:14.4'

    ports:
      - '3002:5432'

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - .docker/db/:/var/lib/postgresql/data/


